### ISSUE TITLE
Workflow cannot work on Macos 12.3 (Apple Silicon)

### ISSUE THREAD

**Issue by Miaoyifei-mz** [maharshmellow/alfred-apple-music-search#1]
Hello, this workflow cannot work on macOS 12.3(Apple Silicon). Here is the debug log:
```
[14:57:54.155] Logging Started...
[14:58:10.098] Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Queuing argument '3'
[14:58:10.170] Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Script with argv '(null)' finished
[14:58:10.173] ERROR: Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Code 1: Traceback (most recent call last):
  File "song.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Miaoyifei-mz** [comment]
I'm not sure if this has anything to do with the removal of Python2.

**Comment by maharshmellow** [comment]
Hi. Sorry, I forgot to mention in the post that you'll need to install requests manually as it's not included with python. Try running `pip install requests` or `pip3 install requests`. 

I don't have access to an Apple Silicon machine right now so I'm not able to test this out - but I don't think this issue would have anything to do with the chip.

**Comment by gagadesu** [comment]
> Hello, this workflow cannot work on macOS 12.3(Apple Silicon). Here is the debug log:
> 
> ```
> [14:57:54.155] Logging Started...
> [14:58:10.098] Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Queuing argument '3'
> [14:58:10.170] Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Script with argv '(null)' finished
> [14:58:10.173] ERROR: Play on Apple Music[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8EA047B4-F4BB-4560-9851-8FF3C244CE3A%3EADEA333D-10C5-4916-8CC3-8DB9FA98591A)] Code 1: Traceback (most recent call last):
>   File "song.py", line 6, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> ```

Tested on M1 Mac.

This is irrelevant with the removal of python2 on macOS 12.3 nor M1 chip, simply run `where python3` in your shell and there are at least two verisons of python3 on your Mac, the bottom one is the system default python3 which Alfred would use. I think you might have installed python3 with something like homebrew or conda, take homebrew for example, you need to specify the correct python3 path in the script filter action, the command should look like:
`/opt/homebrew/bin/python3 song.py "{query}"`

Alternatively, just install `requests` correctly using the system default pip3:
`/usr/bin/pip3 install requests`

And everything works fine.

**Comment by Miaoyifei-mz** [comment]
Thanks a lot! It works when I run `/usr/bin/pip3 install requests`.
